Import ('env')

env.Append(CPPDEFINES='NO_THROW_SPEC')

name = 'vaco-libplugin'
inc = env.Dir('.'), env.Dir('../../../../fideo/'), env.Dir('../../RNAbackends/'), env.Dir('../')
src = env.Glob('*.cpp')
deps = ['fideo', 'vaco-rna-backends', 'vaco-core', 'vaco-libplugin', 'gmock','gtest_main', 'gtest']

env.CreateTest(name, inc, src, deps)
